apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  releaseName: metabase
  chart:
    spec:
      chart: metabase
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 2.4.32  
  interval: 30m
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 1Gi
