apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  releaseName: metabase
  chart:
    spec:
      chart: metabase
      sourceRef:
        kind: HelmRepository
        name: metabase
        namespace: metabase
      version: 0.48.7
  interval: 30m
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 1Gi
