apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  releaseName: metabase
  chart:
    spec:
      chart: metabase
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 5.48.0 # or latest
  interval: 30m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/sun-asterisk-research/helm-charts/blob/master/charts/metabase/values.yaml
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 1Gi