apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  interval: 30m
  releaseName: metabase
  chart:
    spec:
      chart: metabase
      sourceRef:
        kind: HelmRepository
        name: sun-asterisk-research
        namespace: metabase
      interval: 30m
  values:
    # Default values here, can be overridden in overlays 