apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: flux-system
spec:
  chart:
    spec:
      version: 2.4.32
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 1Gi 