apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  chart:
    spec:
      version: 1.0.5
  values:
    image:
      tag: v0.48.7
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      storageClass: ""  # Set to your storage class if needed 