apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  chart:
    spec:
      version: 1.0.6 # Updated to available chart version
  values:
    image:
      tag: v0.48.7 # Example image tag
    # Add other value overrides as needed 