apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  chart:
    spec:
      version: 0.46.6
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: metabase
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 1Gi 