apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  chart:
    spec:
      version: 0.1.0 # Specify the chart version you want
  values:
    image:
      tag: v0.48.7 # Example image tag
    # Add other value overrides as needed 