apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  chart:
    spec:
      version: 1.0.5 # Try earlier chart version
  values:
    image:
      tag: v0.48.7 # Example image tag
    persistence:
      enabled: false 