name: Validate Kubernetes Manifests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint YAML files
        run: |
          sudo apt-get update && sudo apt-get install -y yamllint
          yamllint .

      - name: Lint shell scripts
        run: |
          sudo apt-get install -y shellcheck
          shellcheck script/validate_sh

      - name: Set up yq
        uses: mikefarah/yq@v4.34.2

      - name: Set up kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.3.0'

      - name: Kustomize build (staging)
        run: kustomize build apps/staging

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint Helm charts
        run: |
          helm repo add deliveryhero https://charts.deliveryhero.io/
          helm repo update
          helm lint ./apps/base/metabase

  validate:
    runs-on: ubuntu-latest
    needs: lint-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubeconform
        run: |
          wget -q https://github.com/yannh/kubeconform/releases/download/v0.6.4/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/

      - name: Make validate script executable
        run: chmod +x script/validate_sh

      - name: Run validation script
        run: ./script/validate_sh

  security:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'

      - name: Set up Kubesec
        run: |
          wget -q https://github.com/controlplaneio/kubesec/releases/download/v2.12.0/kubesec_linux_amd64.tar.gz
          tar -xzf kubesec_linux_amd64.tar.gz
          sudo mv kubesec /usr/local/bin/

      - name: Run Kubesec on all YAML manifests
        run: |
          set -e
          for file in $(find . -name '*.yaml'); do
            echo "Scanning $file"
            kubesec scan "$file" || exit 1
          done

      - name: Set up Polaris
        run: |
          wget -q https://github.com/FairwindsOps/polaris/releases/download/7.0.1/polaris_linux_amd64.tar.gz
          tar -xzf polaris_linux_amd64.tar.gz
          sudo mv polaris /usr/local/bin/

      - name: Run Polaris audit
        run: |
          polaris audit --audit-path . 